version: "3"

services:
  app:
    image: bitrixfusion_daemon:bitrixfusion_daemon
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./fusion_daemon:/opt
      - app_node_modules:/opt/node_modules
    environment:
      NODE_ENV: development
      DEBUG: "true"
    network_mode: host

volumes:
  app_node_modules:
