version: "3"

services:
  app:
    image: bitrixfusion_daemon:bitrixfusion_daemon
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    volumes:
      - ./fusion_daemon:/opt
      - app_node_modules:/opt/node_modules
    environment:
      NODE_ENV: development
      DEBUG: "true"
      BITRIX_URL: "https://crm.305plasticsurgery.com/rest/1/sro7d1v0twh44bte"
      REST_ENTRYPOINT: "sro7d1v0twh44bte"

    network_mode: host

volumes:
  app_node_modules:
