FROM node:alpine

LABEL maintainer = Igor Olhovskiy <IgorOlhovskiy@gmail.com>

WORKDIR /opt

COPY ./mock_http_server/package.json /opt/
 
RUN npm install --quiet

VOLUME /opt

ENTRYPOINT ["npm", "start"]